### ISSUE TITLE
Can't sent invite

### ISSUE THREAD

**Issue by kfilipok** [polvora/Inviter#1]
it always have 1 error when i try invite somebody to my group: 0x22: Invite Error: Incorrect Group ID or missing data
"in_steamgroupid" "4425833"

**Comment by polvora** [comment]
It should work with the short group id
Try with the long id:
"in_steamgroupid" "103582791433947241"

I haven't maintained this code for a year so maybe there have been some updates. If the solution i provided doesn't work ill have to reinstall everything.

If you are wondering where i got the long id, i got it from here:
http://steamcommunity.com/groups/csdmpuchku/memberslistxml/?xml=1
That's the group you're pointing right?

**Comment by kfilipok** [comment]
It works with long id. Thx, polvora. You are the best)

**Comment by polvora** [comment]
i honestly didn't expect that. I never tried this plugin/module on a real server.

For the record: Steam updated their servers to only allow long ids instead of both.
