### ISSUE TITLE
Inviter not working

### ISSUE THREAD

**Issue by Rushy0** [polvora/Inviter#2]
Hi,

I have made sure I am putting in the correct username, password and group id. I am using a full steam account (As in it is not limited, aka spending $5 to make it non restarted on steam).

I get this error from the debug:
Response body (144):
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><results><![CDATA[Missing or invalid form session key]]></results></response>na

and in game Session expired, retry to connect

_Edit_ It just takes a while (About 15-20 seconds) to log in. Is it possible to lower this?

**Comment by polvora** [comment]
What response you get in the chat?

**Comment by Rushy0** [comment]
'Session expired, retry to connect'

But like I said in my edit, it just took a while for the session to log in correctly after server start/map change

**Comment by polvora** [comment]
And you are still getting the same error after the log in?
Maybe Steam changed the method to send invites, i haven't touched this code for more than 1 year so it's very likely to happen.

**Comment by Rushy0** [comment]
After waiting a little while it sends correctly. It's just the initial sign in that takes a while

**Comment by polvora** [comment]
Pretty nice is still working, but when you say it takes a while you mean it takes 20 seconds after the map change or after you send the command?

**Comment by Rushy0** [comment]
after map change

**Comment by polvora** [comment]
There's no way to speed it up, 4 requests are made after the map change and it depends on the time your server takes to connect to Steam page.

Also don't forget Steam accounts have a limited number of invites per day, so maybe you want to have multiple accounts.
