### ISSUE TITLE
error

### ISSUE THREAD

**Issue by epickilljoy** [polvora/Inviter#4]
i keep getting There was an error 0x26 while sending your invite :(

**Comment by polvora** [comment]
The plugin is still working i just tested it, so probably there is an error in your cvars or there is other weird error. I need you to post 3 things here:
* The steam group you are inviting to.
* The value of  in_steamgroupid.
* The debug from the console, to do that you just write sc_debug 1 on console and then you send the invite with the command, then open your console and you will see a bunch of information copy and paste all here.

**Comment by epickilljoy** [comment]
in_steamgroupid "103582791431147655"

Preparing request to: 
http://steamcommunity.com/actions/GroupInvite...
Invitee community ID: 
76561198038334951
Verifying login...
Group community ID: 
103582791431147655

============================================================================

Obtaining RSA Key from steamcommunity.com/login/getrsakey...
RSA KEY MODULUS (512): 
e9e2d2f3f78b7750ff31d8bab0b0fc59368cd78cc01e215fe1e77b574bcbfc35aa2177fecc48c4292b850bfcd106adf23db271fd96cf66037c10c101f4ac0ce5e1c471d6caaa0cf95b55ae76df37fc04fb3b9ca399fbb7f1e19e6cc16597a6bd1e5dd9c379859e42ae9d85ca6397a843e426863eaaa600f841e6b9e2b85b97723682b7107adf041043bd36429afdcd6b4876f36994f385c5133ff61303d9c89bcd1a6ad28f492b2d08ddf700f57135ff8e70a3908d0ff736d1c4419f8a6083a21ae7eac24df6752fc6b68943082af915b89e8f3a700ad2e8d79047b934380ff63daf89ff435d57df0ea5c7d99068ca8f62bd005b754711f7870c3b56111aa447
{"success":true,"publickey_mod":"e9e2d2f3f78b7750ff31d8bab0b0fc59368cd78cc01e215fe1e77b574bcbfc35aa2177fecc48c4292b850bfcd106adf23db271fd96cf66037c10c101f4ac0ce5e1c471d6caaa0cf95b55ae76df37fc04fb3b9ca399fbb7f1e19e6cc16597a6bd1e5dd9c379859e42ae9d85ca6397a843e426863eaaa600f841e6b9e2b85b97723682b7107adf041043bd36429afdcd6b4876f36994f385c5133ff61303d9c89bcd1a6ad28f492b2d08ddf700f57135ff8e70a3908d0ff736d1c4419f8a6083a21ae7eac24df6752fc6b68943082af915b89e8f3a700ad2e8d79047b934380ff63daf89ff435d57df0ea5c7d99068ca8f62bd005b754711f7870c3b56111aa447","publickey_exp":"010001","timestamp":"500710500000","token_gid":"4616e8fb8c5f494"}>
<link href="http://steamcommunity-a.akamaihd.net/public/shared/css/shared_global.css?v=aXnR3BCCrqcR" rel="stylesheet" type="text/css" >
<link href="http://steamcommunity-a.akamaihd.net/public/css/globalv2.css?v=wyKWcmeofEub" rel="stylesheet" type="text/css" >
<link href="http://steamcommunity-a.akamaihd.net/public/css/skin_1/fatalerror.css?v=pIYl2w-Jw8th" rel="stylesheet" type="text/css"
RSA KEY EXPONENT (6): 010001
STEAM TIMESTAMP (12): 500710500000

============================================================================

Padded message with PKCS#1 v1.5 standard (512): 
0002281463FF8BAC49FE41B6B3B9F32F84A8AB2B841B41EA54D693E932961DC7B044A4DCA465A6DF624A66A8AF3FE97718B5DF3BB0E622DC7A6EF1D2714E6289C3CC694233EB2097E4E82470A9D2878F2BCCDDD970F53C24EAB7243BFB13EC7C52A3E1ED7D5553C5592D3DEA6F8FC581A6CD1AA18E3C893380CA388CD518C02826A4135BD2AF9E4B8938BB85542C959F92F7D7B8EAB04D8124CE7C8D4565BAD48E9918DC3CD31D1313565168CD9278C1FFC2C06E19D840A9A6CF59562189334EE742C17D3F4BA0A52FFC1EAA9D45CBA01CBC1B3BCA9BD239C692A11F4277F4DC435BC979F23E8611A7D0F975F9E0321ED09C39F330004368616E74696C6C7924
Encrypting passphrase ******** with RSA public key...
Encrypted passphrase with RSA cryptosystem (512): 
34AC63584F301DC289A1C837D862E479D0B8B21C9CBC7F5D560512F6A4FB81D1427BB6A7553741B89B3BE75712582E7F63CCB4DA82924ACFD65442FB6C7E14000CE7F62EBDB6ADD27B98C5813C57771E25A4ACF9602FBBF1D00A1F2E4D261E8E6FEE39D562054D88DF19A7ADF3DB749E8E49888AA3C1AE9A420F8D0E0BBCD98F7CD91D299E8B2487A5D7484EA74D90EE1184E8658C852763DD0F8D7298EBACC30D2EA6D077E0F609B2614DCDDD3E9B4B5680FC1EEF6EB06B48101E2E0D11AB2E8EDA0C20A2128AF16D2C81EA100C66B95C142A8826E19BCF0C0B9057EFE37A5F05B2EEDBCF1E6D8482A8BEA051575A844F3806F66E553112B9868AA8E4675E6D

============================================================================

Logging in to steamcommunity.com/login/dologin/...
Encoded encrypted passphrase with base64 algorithm (344): 
NKxjWE8wHcKJocg32GLkedC4shycvH9dVgUS9qT7gdFCe7anVTdBuJs751cSWC5/Y8y02oKSSs/WVEL7bH4UAAzn9i69tq3Se5jFgTxXdx4lpKz5YC+78dAKHy5NJh6Ob+451WIFTYjfGaet89t0no5JiIqjwa6aQg+NDgu82Y982R0pnoskh6XXSE6nTZDuEYToZYyFJ2PdD41ymOusww0uptB34PYJsmFNzd0+m0tWgPwe726wa0gQHi4NEasujtoMIKISivFtLIHqEAxmuVwUKogm4ZvPDAuQV+/jel8Fsu7bzx5thIKovqBRV1qETzgG9m5VMRK5hoqo5GdebQ==
Success, got response (416): 
{"success":true,"requires_twofactor":false,"login_complete":true,"transfer_urls":["https:\/\/store.steampowered.com\/login\/transfer","https:\/\/help.steampowered.com\/login\/transfer"],"transfer_parameters":{"steamid":"76561198138738586","token":"9C25AC19811E03CFD70D8674ADECAE3AAFF316F0","auth":"c16bfaba7d560af624c051b23013284d","remember_login":false,"token_secure":"CD40330D58DB9905D781F9C1218AB2BCCD26B720"}}3a?
Stored Cookie (251): 
steamCountry=USCf7e18e8eb23c0f8a2ccfb7cd2017afb8; steamLogin=76561198138738586CC9C25AC19811E03CFD70D8674ADECAE3AAFF316F0; path=/; HttpOnly,steamLoginSecure=76561198138738586CCCD40330D58DB9905D781F9C1218AB2BCCD26B720; path=/; secure; HttpOnly
Logging successful, obtaining session token...

============================================================================

Session token successfully acquired (24): 372d431cfd0b82d0beac8277
Current session for Steam ID (19): "76561198138738586"
Appended session token to clean cookie, actual cookie (255): 
Steam_Language=english; sessionid=372d431cfd0b82d0beac8277; steamCountry=USCf7e18e8eb23c0f8a2ccfb7cd2017afb8; steamLogin=76561198138738586CC9C25AC19811E03CFD70D8674ADECAE3AAFF316F0; path=/; HttpOnly,steamLoginSecure=76561198138738586CCCD40330D58

============================================================================

Executing final request...
FFF047There was an error 0x26 FFF047while sending your invite :(
Invite failed. Unknown error response received when sending the group invite.

============================================================================

Final request result: 0 - Error Code : 38
Calling callback...
Callback calling error code: 0 (0: Success)
Removing callback from forward - Result: 1, - Forward Function Count: 0

**Comment by polvora** [comment]
This is an unhandled error, can you install [This version of steamcore.smx](https://github.com/polvora/SteamCore/releases/download/v1.7.1/steamcore.smx) and then post the debug information again?

I can't solve this by myself because i cannot replicate that error.

**Comment by epickilljoy** [comment]
Found the issue, account i was using was a limited account https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663

**Comment by polvora** [comment]
weird that should be error 0x27, ill address this on next release. thanks.

**Comment by polvora** [comment]
I need more feedback on this. opening issue in steamcore repository (https://github.com/polvora/SteamCore/issues/6)
